[project]
name = "test-de"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=46.0.3",
    "kafka>=1.3.5",
    "mysql-connector>=2.2.9",
    "pandas>=2.3.3",
    "pymysql>=1.1.2",
]
