{
 "title": "Replicator",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(confluent_replicator_task_metrics_latency, topic_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(confluent_replicator_task_metrics_latency, instance)"
    }
   },
   {
    "name": "connector",
    "label": "connector",
    "query": {
     "query": "label_values(confluent_replicator_task_metrics_latency, name)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(confluent_replicator_task_metrics_info,env)"
    }
   },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Connect Cluster",
    "query": {
     "query": "label_values(confluent_replicator_task_metrics_info,kafka_connect_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"} >= 0) by (topic_name)",
     "legendFormat": "{{ topic_name }} "
    }
   ]
  },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"} >= 0) by (topic_name)",
     "legendFormat": "{{ topic_name }} "
    }
   ]
  },
  {
   "title": "Replication Latency (Topic)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(avg_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0) by (topic_name)"
    },
    {
     "expr": "max(max_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0) by (topic_name)"
    },
    {
     "expr": "min(min_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\"}[$__interval]) >= 0) by (topic_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag (Topic)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(avg_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0) by (topic_name)"
    },
    {
     "expr": "max(max_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0) by (topic_name)"
    },
    {
     "expr": "min(min_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0) by (topic_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Latency (Partition)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0"
    },
    {
     "expr": "max_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0"
    },
    {
     "expr": "min_over_time(confluent_replicator_task_metrics_latency{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag (Partition)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0"
    },
    {
     "expr": "max_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0"
    },
    {
     "expr": "min_over_time(confluent_replicator_task_metrics_message_lag{topic_name=~\"$topic\", instance=~\"$instance\", name=~\"$connector\", env=~\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"}[$__interval]) >= 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}